version: '{build}-{branch}'
branches:
  only:
    - master

skip_tags: true

environment:
  matrix:
    - image: Visual Studio 2015
      configuration: Release
      arch: 64
    - image: Visual Studio 2015
      configuration: Debug
      arch: 64
    - image: Visual Studio 2017
      configuration: Release
      arch: 64
    - image: Visual Studio 2017
      configuration: Debug
      arch: 64

clone_folder: c:\projects\catboost

install:
  - git submodule update --init --recursive

build_script:
  - |
    cd c:\projects\catboost
    call ya.bat make --verbose --stat -rttt catboost\app catboost\pytest
