on: 1.0.{build}-{branch}

branches:
  only:
    - master

skip_tags: true
os: Visual Studio 2015

configuration:
  - Debug
  - Release

clone_folder: c:\projects\catboost

install:
  - git submodule update --init --recursive

build_script:
  - |
    cd c:\projects\catboost
    call "ya.bat" -rttt catboost\app catboost\pytest
