dist: trusty
sudo: false
language: cpp
cache: apt
cache:
  apt: true
  directories:
    - $HOME/.ya

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libc6-dev
      - python-dev
      - python3-dev

matrix:
  include:
    - os: linux
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='clang-linux-x86_64-debug'
    - os: osx
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='clang-darwin-x86_64-debug'
    - os: linux
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='clang-linux-x86_64-release'
    - os: linux
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='python2-linux-x86_64-release'
    - os: linux
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='python3-linux-x86_64-release'
    - os: osx
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='clang-darwin-x86_64-release'
    - os: osx
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='python2-darwin-x86_64-release'
    - os: osx
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='python3-darwin-x86_64-release'

script:
  - |
    set -x
    set -e
    if [ "${CB_BUILD_AGENT}" == 'clang-linux-x86_64-debug' ]; then
        ./ya make --stat -d -j 1 catboost/app catboost/pytest;
    fi

    if [ "${CB_BUILD_AGENT}" == 'clang-darwin-x86_64-debug' ]; then
        ./ya make --stat -d -j 1 catboost/app catboost/pytest;
    fi

    if [ "${CB_BUILD_AGENT}" == 'clang-linux-x86_64-release' ]; then
        ./ya make --stat -rttt -j 1 catboost/app catboost/pytest;
    fi

    if [ "${CB_BUILD_AGENT}" == 'clang-darwin-x86_64-release' ]; then
        ./ya make --stat -rttt -j 1 catboost/app catboost/pytest;
    fi

    if [ "${CB_BUILD_AGENT}" == 'python2-linux-x86_64-release' ]; then
        cd catboost/python-package;
        python2.7 ./mk_wheel.py;
    fi

    if [ "${CB_BUILD_AGENT}" == 'python2-darwin-x86_64-release' ]; then
        cd catboost/python-package;
        python2.7 ./mk_wheel.py;
    fi

    if [ "${CB_BUILD_AGENT}" == 'python3-linux-x86_64-release' ]; then
        cd catboost/python-package;
        python3.4 ./mk_wheel.py;
    fi

    if [ "${CB_BUILD_AGENT}" == 'python3-darwin-x86_64-release' ]; then
        cd catboost/python-package;
        python3.4 ./mk_wheel.py;
    fi
