sudo: false
cache:
  apt: true
  directories:
    - $HOME/.ya

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libc6-dev
      - python-dev
      - python3-dev

matrix:
  include:
    - os: linux
      language: cpp
      dist: trusty
      env: CB_BUILD_AGENT='clang-linux-x86_64-debug'
    - os: linux
      language: cpp
      dist: trusty
      env: CB_BUILD_AGENT='clang-linux-x86_64-release'
    - os: linux
      language: python
      dist: trusty
      python: 2.7
      env: CB_BUILD_AGENT='python2-linux-x86_64-release'
    - os: linux
      language: python
      dist: trusty
      python: 3.4
      env: CB_BUILD_AGENT='python3-linux-x86_64-release'
    - os: osx
      language: cpp
      osx_image: xcode8.3
      env: CB_BUILD_AGENT='clang-darwin-x86_64-debug'
    - os: osx
      language: cpp
      osx_image: xcode8.3
      env: CB_BUILD_AGENT='clang-darwin-x86_64-release'
    - os: osx
      # python runtime is not available yet [1], so we have to prepare sandbox by ourselves
      #
      # [1] https://github.com/travis-ci/travis-ci/issues/2312
      language: generic
      osx_image: xcode8.3
      before_install: brew update
      install: |
        brew install python
        virtualenv py2env -p python2
        source py2env/bin/activate
      env: CB_BUILD_AGENT='python2-darwin-x86_64-release'
    - os: osx
      language: generic
      osx_image: xcode8.3
      before_install: brew update
      install: |
        brew install python3
        virtualenv py3env -p python3
        source py3env/bin/activate
      env: CB_BUILD_AGENT='python3-darwin-x86_64-release'


before_script: |
    # `ya` provides it's own compiler toolchains, `CC` and CXX` environment variables will override
    # them so we have to unset them.
    unset CC
    unset CXX

script: ./ci/travis/script.sh
