dist: trusty
sudo: false
language: cpp
cache: apt
cache:
  apt: true
  directories:
    - $HOME/.ya

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libc6-dev
      - python-dev
      - python3-dev

matrix:
  include:
    - os: linux
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='clang-linux-x86_64-debug'
    - os: linux
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='python2-linux-x86_64-debug'
    - os: linux
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='python3-linux-x86_64-debug'
    - os: osx
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='clang-darwin-x86_64-debug'
    - os: osx
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='python3-darwin-x86_64-debug'
    - os: osx
      before_install:
        - |
          unset CC
          unset CXX
      env: CB_BUILD_AGENT='python3-darwin-x86_64-debug'

script:
  - |
    if [ "${CB_BUILD_AGENT}" == 'clang-linux-x86_64-debug' ]; then
        ./ya make -dttt catboost/app catboost/pytest;
    fi

    if [ "${CB_BUILD_AGENT}" == 'clang-darwin-x86_64-debug' ]; then
        ./ya make -dttt catboost/app catboost/pytest;
    fi

    if [ "${CB_BUILD_AGENT}" == 'python2-linux-x86_64-debug' ]; then
        ./ya make -dttt -DUSE_ARCADIA_PYTHON=no -DPYTHON_INCLUDE_DIR='/usr/include/python2.7' -DPYTHON_LIBRARY='python2.7' catboost/python-package;
    fi

    if [ "${CB_BUILD_AGENT}" == 'python2-darwin-x86_64-debug' ]; then
        ./ya make -dttt -DUSE_ARCADIA_PYTHON=no -DPYTHON_INCLUDE_DIR='/usr/include/python2.7' -DPYTHON_LIBRARY='python2.7' catboost/python-package;
    fi

    if [ "${CB_BUILD_AGENT}" == 'python3-linux-x86_64-debug' ]; then
        ./ya make -dttt -DUSE_ARCADIA_PYTHON=no -DPYTHON_INCLUDE_DIR='/usr/include/python3.4' -DPYTHON_LIBRARY='python3.4' catboost/python-package;
    fi

    if [ "${CB_BUILD_AGENT}" == 'python3-darwin-x86_64-debug' ]; then
        ./ya make -dttt -DUSE_ARCADIA_PYTHON=no -DPYTHON_INCLUDE_DIR='/usr/include/python3.4' -DPYTHON_LIBRARY='python3.4' catboost/python-package;
    fi
